apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "ibm-iam-policy-operator"
    app.kubernetes.io/managed-by: "ibm-iam-policy-operator"
    app.kubernetes.io/name: "ibm-iam-policy-operator"
  name: ibm-iam-policy-operator
  namespace: test
spec:
  selector:
    matchLabels:
      name: ibm-iam-policy-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-iam-policy-operator
        app.kubernetes.io/instance: ibm-iam-policy-operator
        app.kubernetes.io/managed-by: "ibm-iam-policy-operator"
        app.kubernetes.io/name: "ibm-iam-policy-operator"
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-iam-policy-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - command:
            - /manager
          args:
            - --metrics-addr=:8383
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: IAM_POLICY_CONTROLLER_IMAGE
              value: quay.io/opencloudio/iam-policy-controller@sha256:0f20b1abe1ac4926b0d58ac30863e015f4f75f0fcc166c398a5348e1e2e8fa27
          image: quay.io/opencloudio/ibm-iam-policy-operator:latest
          imagePullPolicy: Always
          name: ibm-iam-policy-operator
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      terminationGracePeriodSeconds: 10
