# permissions for end users to view policycontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policycontroller-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - policycontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - policycontrollers/status
  verbs:
  - get
