apiVersion: iam.policies.ibm.com/v1alpha1
kind: IamPolicy
metadata:
  name: iam-policy-example
  labels:
    app.kubernetes.io/instance: ibm-iam-policy-operator
    app.kubernetes.io/managed-by: ibm-iam-policy-operator
    app.kubernetes.io/name: ibm-iam-policy-operator
    category: System-Integrity
spec:
  #Include are the namespaces for which you want to watch cluster administrator role and IAM rolebinings, while exclude are the namespaces you explicitly do not want to watch
  namespaceSelector:
    include: ["ibm-common-services"]
    exclude: ["kube-system"]
    #labelSelector:
    #env: "production"
  remediationAction: inform # enforce or inform
  severity: medium
  maxClusterRoleBindingUsers: 5
  maxRoleBindingViolationsPerNamespace: 2